== Testing Erlang

:Author:    Zachary Kessin
:Email:     zkessin@gmail.com


Erlang has existed for a long time but has only recently become a
trending language that is being used in more and more places as people
find that Erlang is the perfect fit for building networked concurrent
applications for the web and other places.

However in order to make a high performance scalable applications
developers need to test those applications. The goal of this book is
to introduce the reader to how to do different types of testing in
Erlang. 

This book starts with using EUnit for building Unit Tests in
Erlang. It will then move on to other kinds of testing in
Erlang. Including Statistical tests with QuickCheck, Type Checking
with Dialyzer, Setting up CI with Jenkins or Travis, building
performance tests and more.


=== Chapters

* link:preface.asciidoc.html[]
* link:eunit.asciidoc.html[Using EUnit]
* link:rebar.asciidoc.html[Building With Rebar]
* link:advanced_eunit.asciidoc.html[Advanced Topics in EUnit]
* link:eunit_auto_test_runner.asciidoc.html[Run tests Automaticly When Files change]
* link:eunit_tdd_practicum.asciidoc.html[Lets do some TDD Together]
* link:ci.asciidoc.html[CI with Travis and Jenkins]
* link:performance_tests.asciidoc.html[Performance and Stress Tests]
* link:chaos_monkey.asciidoc.html[Testing Resilience with a Chaos Monkey]

=== Chapters that will probably be in the 2nd Edition
* link:common_test.asciidoc.html[Common Test]
* link:quick_check.asciidoc.html[Quick Check]
* link:prop_er.asciidoc.html[PropEr]
* link:dialyzer.asciidoc.html[Checking types with Dialyzer]

==== New Chapters 
Add any new chapter links here, they will be moved up later
