== Testing Erlang

:Author:    Zachary Kessin
:Email:     zkessin@gmail.com


Erlang has existed for a long time but has only recently become a
trending language that is being used in more and more places as people
find that Erlang is the perfect fit for building networked concurrent
applications for the web and other places.

However in order to make a high performance scalable applications
developers need to test those applications. The goal of this book is
to introduce the reader to how to do different types of testing in
Erlang. 

This book starts with using EUnit for building Unit Tests in
Erlang. It will then move on to other kinds of testing in
Erlang. Including Statistical tests with QuickCheck, Type Checking
with Dialyzer, Setting up CI with Jenkins or Travis, building
performance tests and more.


=== Chapters

* link:00_preface.html[Preface]
* link:01_rebar.html[Building With Rebar]
* link:02_eunit.html[Eunit]
* link:03_common_test.html[Common Test]
* link:04_dialyzer.html[Dialyzer]
* link:05_proper.html[Proper]
* link:06_quick_check.html[Quick Check]
* link:07_testing_a_fsm.html[Testing a FSM With Properties]
* link:08_wrangler.html[Wrangler]
* link:09_concuerror.html[Concerrer]
* link:10_ci.html[Contious Integration]
* link:11_best_practices.html[Best Practice]




