
== Mocking With Meck

If your code is anything like mine you will find that many of your
functions depend heavily on external functions, which may come from
the Erlang Standard Library or from other modules that may have been
written in house or pulled from the web. 

In an ideal world a test should be able to isolate your code from the
modules it calls so that you can test your code without having to
worry about questions like, the status of an external API or the
complex behavior of a library method.

To do that we use a mocking library such as +meck+ which can take
functions in other modules and replace them with test functions that
allow a simplified truth table.  

Meck provides mocks on the level of the Erlang module, before running
a test you must setup mocking for that library, then remove it when
done. 

For example if you want to mock the webmachine +wrq:req_body/1+
function you might use code like this in this example. 

Here we setup the test with +meck:new(wrq)+ which tells meck to mock
that module, then in the body of the test we use +meck:expect/3+ to
tell it when the wrq:req_body/1 function is called to call our test
function which returns a set binary to the caller. After this we can
call +wrq:req_body/1+ and know exactly what it will return.


.setting up meck.erl
----
include::meck/src/meck_simple.erl[source, erlang]
----


=== More complex Meck Examples

=== Places Meck can go wrong
